#page title
page_title                                : Twoot it! – Schedule Posts                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6472669260                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/app/apple-store/id6472669260?pt=549314&ct=crosscraft.app&mt=8                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://github.com/FlineDev/CrossCraft-LandingPage/raw/main/downloads/PressKit-v2.0.zip                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : "CrossCraft: Custom Crosswords"                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : "Freemium"                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Create Personalized Puzzles!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Cihat Gündüz                                
your_link                                 : https://fline.dev/about/?ref=crosscraft.app
your_city                                 : the EU 🇪🇺                                
email_address                             : crosscraft@fline.dev
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : CrossCraftApp
github_username                           : Jeehut
youtube_username                          : FlineDev
mastodon_link                             : https://iosdev.space/@CrossCraftApp



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Varied Topics
    description                           : Dive into an extensive range of topics from categories like General Knowledge (like Pop Culture), Movie Franchises (like Harry Potter), Sports (like Football), or Programming (like Flutter).
    fontawesome_icon_name                 : lightbulb
    
  - title                                 : Personalized Puzzles
    description                           : Blend provided topics with your own question-answer pairs to craft unique and meaningful crosswords, perfect for educators, parents, or event organizers.
    fontawesome_icon_name                 : puzzle-piece

  - title                                 : Multiple Sizes and Shapes
    description                           : Choose from 5 sizes (XS to XL) and 3 shapes (square, portrait, landscape) to suit any occasion or challenge level.
    fontawesome_icon_name                 : expand

  - title                                 : Adjustable Difficulty
    description                           : Tailor the challenge with 3 difficulty levels, ensuring fun and engagement for all ages and skill levels.
    fontawesome_icon_name                 : sliders-h

  - title                                 : Play Anytime, Anywhere
    description                           : Engage with crosswords directly within the app, whether you're online or offline, thanks to local on-device generation.
    fontawesome_icon_name                 : mobile

  - title                                 : Export and Share
    description                           : Easily export and share your creations, or print them out for physical play. Ideal for special events like birthdays, Christmas gatherings, and more.
    fontawesome_icon_name                 : share-alt

  - title                                 : Limitless Possibilities
    description                           : With unlimited crossword generation, your puzzle potential is endless.
    fontawesome_icon_name                 : infinity

  - title                                 : Inclusive Language Support
    description                           : Enjoy the app and its puzzles in 7 different languages, making it accessible and enjoyable for a diverse global audience.
    fontawesome_icon_name                 : globe


# Theme Settings
topbar_color                              : "#091B30"
topbar_transparency                       : 0.35
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#0E2840"
cover_overlay_transparency                : 0.77

device_color                              : gray                                     # Set to: gold, gray, purple, or silver.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
