#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1660521050                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/app/apple-store/id1660521050?pt=549314&ct=twoot-it.app&mt=8                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://github.com/FlineDev/Twoot-it-LandingPage/raw/main/downloads/PressKit-v1.0.zip                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : "Freemium"                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Cross-Post to Twitter & Mastodon

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Cihat Gündüz                                
your_link                                 : https://fline.dev/about/?ref=twoot-it.app
your_city                                 : the EU 🇪🇺                                
email_address                             : twoot.it@fline.dev
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : Twoot_it
github_username                           : Jeehut
youtube_username                          : FlineDev
mastodon_link                             : https://iosdev.space/@Twoot_it



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Cross-Post to Twitter and Mastodon
    description                           : Post updates to Twitter and Mastodon simultaneously, from a single app.
    fontawesome_icon_name                 : random
    
  - title                                 : Image and Video Attachments
    description                           : Enhance your social media posts, making your moments more engaging and compelling.
    fontawesome_icon_name                 : paperclip

  - title                                 : Interactive Polls
    description                           : Empower audience participation and gather insights with poll support, fostering engagement and sparking discussions.
    fontawesome_icon_name                 : poll

  - title                                 : Schedule Posts
    description                           : Take control of your social media presence by scheduling posts for later, ensuring consistent and timely content delivery.
    fontawesome_icon_name                 : clock

  - title                                 : Tailor Your Posts for Each Platform
    description                           : Customize posts with platform-specific text replacements, avoiding dead links.
    fontawesome_icon_name                 : exchange
  
  - title                                 : User-Friendly Interface
    description                           : Intuitive interface for content creators, influencers, and professionals, ensuring a seamless experience.
    fontawesome_icon_name                 : mobile

  - title                                 : FREE tier available
    description                           : Cross-post for free by sharing your Mastodon post to Twitter through a built-in workaround.
    fontawesome_icon_name                 : piggy-bank

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
